### ISSUE TITLE
Cannot set a variable outside of a block?

### ISSUE THREAD

**Issue by jkcclemens** [jtwig/jtwig#297]
Here's a [gist](https://gist.github.com/jkcclemens/07b7db893874c62e3aca) with the relevant files.

I've got jtwig (3.1.1) working with Spring in an embedded Jetty server. Before I rewrote my twig files to use the extends tag, it was all rendering fine.

However, it appears as if having a set tag outside of a block is making an NPE be thrown:
```
java.lang.NullPointerException
	at com.lyncode.jtwig.mvc.JtwigView.renderMergedTemplateModel(JtwigView.java:100)
	at org.springframework.web.servlet.view.AbstractTemplateView.renderMergedOutputModel(AbstractTemplateView.java:167)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1244)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1027)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:971)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```
Removing the set tag makes the NPE stop being thrown, but then the index file is only partially rendered; some blocks do not appear to be overridden:
```html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title></title>
  <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css"/>
</head>
<body>

  <h1></h1>
  

</body>
</html>
```
Here, the title block was overridden, but the content block appears to have done nothing. With some more testing, removing the title block and the set line makes the content block appear normally.

I feel as if I'm doing something wrong, but I don't know what. It seems counter-intuitive to me that you cannot set a variable outside of a block.

Doing the following makes everything perform as expected:
```twig
{% block title %}{% set nick = (humanity.getBot.getNick is null) ? "TheHumanity" : humanity.getBot.getNick %}{{ nick }}{% endblock %}
```

Again, let me know if this is just a restriction of twig that I'm unaware of.

**Comment by thomas-p-wilson** [comment]
Hi @jkcclemens. The problem you are describing is a known issue. It was resolved as of PR #154 and is also referenced in #273. You'll find that the issue should be resolved on master. Not sure when 4.0.0 is schedule for release though. I'll look into backporting the fix to the 3.x line.

**Comment by jkcclemens** [comment]
Ah, I had tried searching for it, but I didn't find anything. Thanks for letting me know! I'm using the Maven artifact for 3.1.1, so it would be awesome if it could be backported.

**Comment by thomas-p-wilson** [comment]
Yeah, I've tried searching for that a few times. It doesn't help that 'set'
is such a common word! @lyncodev, what do you think about backporting the
set/extends fix to the 3.x branch?

**Comment by lyncodev** [comment]
New version fixes this (test proving it https://github.com/jtwig/jtwig-core/blob/master/src/test/java/org/jtwig/integration/issues/Issue297Test.java)
