### ISSUE TITLE
Defining prefix/suffix of the resolver not doing anything

### ISSUE THREAD

**Issue by Litarvan** [jtwig/jtwig#317]
Hey, i'm using Spring Boot 1.4 with Spring MVC 4.3.2 and JTwig Core 5.61/Web 1.55/Spring 5.59 with Gradle

Here is my configuration class, i defined a prefix and a suffix for the view resolver :

``` java
@Configuration
@EnableWebMvc
public class MyWebConfig extends WebMvcConfigurerAdapter implements JtwigViewResolverConfigurer
{
    @Bean
    public ViewResolver viewResolver()
    {
        JtwigViewResolver viewResolver = new JtwigViewResolver();
        viewResolver.setPrefix("web:/WEB-INF/templates/");
        viewResolver.setSuffix(".twig.html");

        return viewResolver;
    }

    @Override
    public void configure(JtwigViewResolver viewResolver) {
        viewResolver.setRenderer(new JtwigRenderer(EnvironmentConfigurationBuilder.configuration()
                .extensions().add(new SpringAssetExtension()).and()
                .build()));
    }
}
```

But then, using this in a controller :

``` java
    @RequestMapping(value = "/login", method = RequestMethod.GET)
    public String loginGet(Model model)
    {
        return "gde/login";
    }
```

I get this error : org.jtwig.resource.exceptions.ResourceNotFoundException: Resource '/templates/gde/login.twig' not found

My template is in src/main/resources/WEB-INF/templates/gde/login.twig.html
I tested, when putting it in src/main/resources/templates/gde/login.twig it works, so the prefix does nothing.

Also, in the logs i get : 

```
2016-09-18 22:23:47.261  INFO 14642 --- [           main] o.j.spring.boot.JtwigAutoConfiguration   : Jtwig View Resolver configurer provided, applying custom configuration
2016-09-18 22:23:47.264  INFO 14642 --- [           main] o.j.spring.boot.JtwigAutoConfiguration   : Jtwig View Resolver bean added to the context
```

So, it gets the configuration.

**Comment by lyncodev** [comment]
By using the module jtwig-spring-boot-starter with spring boot auto configuration enabled, the bean JtwigViewResolver is created and injected into the context, there is no need to instantiate a new one. @Litarvan in your example, you are just defining a new viewResolver which Spring will append to the view resolution chain. However, because the jtwig view resolver injected by the mentioned module throws an exception, the resolution chain is interrupted and your declared view resolver doesn't even get triggered.

If you're trying to setup only one JtwigViewResolver bean, try the following:

```java
@Configuration
@EnableWebMvc
public class MyWebConfig extends WebMvcConfigurerAdapter implements JtwigViewResolverConfigurer
{
    @Override
    public void configure(JtwigViewResolver viewResolver) {
        viewResolver.setPrefix("web:/WEB-INF/templates/");
        viewResolver.setSuffix(".twig.html");
        viewResolver.setRenderer(new JtwigRenderer(EnvironmentConfigurationBuilder.configuration()
                .extensions().add(new SpringAssetExtension()).and()
                .build()));
    }
}
```

However, if you want to specify multiple instances of this view resolver, then this is, at the moment, a limitation with the framework.

**Comment by Litarvan** [comment]
Seems logic, i don't want to create multiple resolvers. I did what you said, but now i'm getting this : 
```
java.lang.NullPointerException: Argument 'input' must not be null
	at org.parboiled.common.Preconditions.checkArgNotNull(Preconditions.java:208) ~[parboiled-core-1.1.7.jar:1.1.7]
	at org.parboiled.parserunners.AbstractParseRunner.run(AbstractParseRunner.java:75) ~[parboiled-core-1.1.7.jar:1.1.7]
	at org.jtwig.parser.parboiled.ParboiledJtwigParser.parse(ParboiledJtwigParser.java:50) ~[jtwig-core-5.61.jar:na]
	at org.jtwig.parser.cache.InMemoryConcurrentPersistentTemplateCache.get(InMemoryConcurrentPersistentTemplateCache.java:39) ~[jtwig-core-5.61.jar:na]
	at org.jtwig.parser.CachedJtwigParser.parse(CachedJtwigParser.java:19) ~[jtwig-core-5.61.jar:na]
	at org.jtwig.JtwigTemplate.render(JtwigTemplate.java:96) ~[jtwig-core-5.61.jar:na]
	at org.jtwig.JtwigTemplate.render(JtwigTemplate.java:79) ~[jtwig-core-5.61.jar:na]
	at org.jtwig.web.servlet.JtwigDispatcher.render(JtwigDispatcher.java:49) ~[jtwig-web-1.55.jar:na]
	at org.jtwig.spring.JtwigView.renderMergedTemplateModel(JtwigView.java:15) ~[jtwig-spring-5.59.jar:na]
	at org.springframework.web.servlet.view.AbstractTemplateView.renderMergedOutputModel(AbstractTemplateView.java:167) ~[spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303) ~[spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1257) ~[spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1037) ~[spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:980) ~[spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897) ~[spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) ~[spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) ~[tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) ~[spring-webmvc-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) ~[tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230) ~[tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.5.4.jar:8.5.4]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) ~[spring-web-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108) [tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:522) [tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349) [tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1110) [tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:785) [tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1425) [tomcat-embed-core-8.5.4.jar:8.5.4]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.4.jar:8.5.4]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_65]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.4.jar:8.5.4]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
```

**Comment by lyncodev** [comment]
@Litarvan that happens because jtwig can't find the template. Clearly this is not a developer friendly exception (null pointer). jtwig/jtwig-web#22 was merged to make it more clear what went wrong.

**Comment by Litarvan** [comment]
Without the prefix, it works, but when i put the templates in the WEB-INF/ directory and i set the prefix as "WEB-INF" (just this), it doesn't work :/
