### ISSUE TITLE
Method resolution cache corruption / bug in resolution caching

### ISSUE THREAD

**Issue by janoszen** [jtwig/jtwig#336]
When specifying two different subclasses of an abstract class as a parameter for a method, the method resolution does not work correctly.

Sample code:

```
public abstract class AbstractModel {
    public abstract String getKey();
}
```

```
public class SubModelA extends AbstractModel {
    @Override
    public String getKey() {
        return "A";
    }
}
```

```
public class SubModelB extends AbstractModel {
    @Override
    public String getKey() {
        return "B";
    }
}
```

```
public class Test {
    public static void main(String[] args) {
        JtwigTemplate template = JtwigTemplate.classpathTemplate("templates/example.twig");
        JtwigModel model = JtwigModel.newModel().with("a", new SubModelA());
        model = model.with("b", new SubModelB());
        template.render(model, System.out);
    }
}
```

```
{% import _self as s %}

{% macro test(model) %}
    {{ model.getKey() }}
{% endmacro %}

{{ s.test(a) }}
{{ s.test(b) }}
```

It results in this exception (with strict mode):

```
Exception in thread "main" org.jtwig.exceptions.CalculationException: classpath:templates/example.twig (Line: 4, Column: 13) -> Cannot extract property 'getKey' out of 'model'
	at org.jtwig.render.expression.calculator.operation.binary.calculators.selection.SelectionOperationCalculator.calculate(SelectionOperationCalculator.java:33)
	at org.jtwig.render.expression.calculator.operation.binary.BinaryOperationService.calculate(BinaryOperationService.java:20)
	at org.jtwig.render.expression.calculator.BinaryOperationExpressionCalculator.calculate(BinaryOperationExpressionCalculator.java:9)
	at org.jtwig.render.expression.calculator.BinaryOperationExpressionCalculator.calculate(BinaryOperationExpressionCalculator.java:6)
	at org.jtwig.render.expression.CalculateExpressionService.calculate(CalculateExpressionService.java:14)
	at org.jtwig.render.node.renderer.OutputNodeRender.render(OutputNodeRender.java:15)
	at org.jtwig.render.node.renderer.OutputNodeRender.render(OutputNodeRender.java:10)
	at org.jtwig.render.node.RenderNodeService.render(RenderNodeService.java:22)
	at org.jtwig.render.node.renderer.CompositeNodeRender.render(CompositeNodeRender.java:21)
	at org.jtwig.render.node.renderer.CompositeNodeRender.render(CompositeNodeRender.java:13)
	at org.jtwig.render.node.RenderNodeService.render(RenderNodeService.java:22)
	at org.jtwig.macro.render.MacroRender.render(MacroRender.java:32)
```

Upon inspection the source exception is thrown in MethodPropertyResolver.java:31 because requestContext() is an instance of `SubModelB`, but `javaMethod` refers to `getKey()` from `SubModelA`. 

It seems that `CachedSelectionPropertyResolver` (line 28) caches based on the code position and the first encounter with a method name. It does not account for the fact that the same code position with the same method name can refer to a different class.

It seems to work as intended when configured with `NoSelectionPropertyResolverCache`.

**Since Twig is based on PHP, which has duck typing, I think caching the resolution in this way is a mistake and will always result in bugs.**

The bug arose when I was trying to write a form helper macro that was able to handle multiple form field types.

**Comment by lyncodev** [comment]
Good spot. Will be better to have the cache disabled by default. Also planning on adding this as documentation for the resolution cache.

**Comment by maxbechtold** [comment]
I also experienced this issue, and it's not trivial to trace this down.
In particular, since the root exception is something like `java.lang.IllegalArgumentException: object is not an instance of declaring class` and is not passed up to the user - that's the very least that should be fixed.

Thanks @janoszen for the hint with the `NoSelectionPropertyResolverCache`, which I want to detail for others:

`EnvironmentConfigurationBuilder.configuration().propertyResolver().withCache(NoSelectionPropertyResolverCache.noSelectionPropertyResolverCache());`
