### ISSUE TITLE
Problems dealing with polymorphic Classes

### ISSUE THREAD

**Issue by MaZderMind** [jtwig/jtwig#343]
It seems as if JTwig caches the Type of an expression and expects all following Instances to be of the same Type. This is not necessarily the case, as the following example demonstrates. It seems to not be possible to use JTwig with polymorphic object models.

There are ways around when disabling the Template-Cache and moving the use of the polymorphic object into another twig-file, but this would require to turn off template caching, which is undesirable.

Example-Code (Java8):
```java
import java.util.List;

import org.jtwig.JtwigModel;
import org.jtwig.JtwigTemplate;
import org.parboiled.common.ImmutableList;

abstract class ParentClass {
	public abstract String getType();
}

class ConcreteClassA extends ParentClass {
	public String getType() {
		return "A";
	}
}

class ConcreteClassB extends ParentClass {
	public String getType() {
		return "B";
	}
}

public class Main {

	public static void main(String[] args) {
		List<ParentClass> list = ImmutableList.of(
			new ConcreteClassA(),
			new ConcreteClassB(),
			new ConcreteClassA()
		);

		JtwigTemplate template = JtwigTemplate.classpathTemplate("main.twig");
		JtwigModel model = JtwigModel.newModel()
				.with("var", "World")
				.with("list", list);

		template.render(model, System.out);
	}
}
```

```twig
Variable: {{ var }}

List of Objects of different concrete Classes
{% for item in list %}
   - {{ item.type }}
{% endfor %}
```

Output:
```
Variable: World

List of Objects of different concrete Classes

   - A

   - 

   - A
```

Exception:
```
17:46:04.811 [main] DEBUG o.j.p.r.MethodPropertyResolver - Unable to retrieve value from method org.jtwig.reflection.model.java.JavaMethod@773c0293 with arguments []
java.lang.IllegalArgumentException: object is not an instance of declaring class
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jtwig.reflection.model.java.JavaMethod.invoke(JavaMethod.java:33)
	at org.jtwig.property.resolver.MethodPropertyResolver.resolve(MethodPropertyResolver.java:31)
	at org.jtwig.property.selection.SelectionPropertyResolveService.resolve(SelectionPropertyResolveService.java:19)
	at org.jtwig.property.selection.CachedSelectionPropertyResolver.resolve(CachedSelectionPropertyResolver.java:24)
	at org.jtwig.render.expression.calculator.operation.binary.calculators.selection.SelectionOperationCalculator.calculate(SelectionOperationCalculator.java:22)
	at org.jtwig.render.expression.calculator.operation.binary.BinaryOperationService.calculate(BinaryOperationService.java:20)
	at org.jtwig.render.expression.calculator.BinaryOperationExpressionCalculator.calculate(BinaryOperationExpressionCalculator.java:9)
	at org.jtwig.render.expression.calculator.BinaryOperationExpressionCalculator.calculate(BinaryOperationExpressionCalculator.java:6)
	at org.jtwig.render.expression.CalculateExpressionService.calculate(CalculateExpressionService.java:14)
	at org.jtwig.render.node.renderer.OutputNodeRender.render(OutputNodeRender.java:15)
	at org.jtwig.render.node.renderer.OutputNodeRender.render(OutputNodeRender.java:10)
	at org.jtwig.render.node.RenderNodeService.render(RenderNodeService.java:22)
	at org.jtwig.render.node.renderer.CompositeNodeRender.render(CompositeNodeRender.java:21)
	at org.jtwig.render.node.renderer.CompositeNodeRender.render(CompositeNodeRender.java:13)
	at org.jtwig.render.node.RenderNodeService.render(RenderNodeService.java:22)
	at org.jtwig.render.node.renderer.ForLoopNodeRender.render(ForLoopNodeRender.java:49)
	at org.jtwig.render.node.renderer.ForLoopNodeRender.render(ForLoopNodeRender.java:20)
	at org.jtwig.render.node.RenderNodeService.render(RenderNodeService.java:22)
	at org.jtwig.render.node.renderer.CompositeNodeRender.render(CompositeNodeRender.java:21)
	at org.jtwig.render.node.renderer.CompositeNodeRender.render(CompositeNodeRender.java:13)
	at org.jtwig.render.node.RenderNodeService.render(RenderNodeService.java:22)
	at org.jtwig.JtwigTemplate.render(JtwigTemplate.java:94)
	at org.jtwig.JtwigTemplate.render(JtwigTemplate.java:79)
	at Main.main(Main.java:37)
```

Researching deeper, it seems that `SelectionPropertyResolverCache` does not take the Object-Class into scope when checking for a cached PropertyResolver when it should, as a most PropertyResolvers reference a `JavaMethod` or a `JavaField`, thus being only valid for a single Class.

**Comment by MaZderMind** [comment]
This is related to #336 for which a test exists, which actually ensures that the return-value in this case is an empty string (see https://github.com/jtwig/jtwig-core/blob/master/src/test/java/org/jtwig/integration/issues/Issue336Test.java#L29).

Following the Issues comments this is not desired but the test is there to document the current (broken) behavior.
