### ISSUE TITLE
java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by jantajov** [jtwig/jtwig#346]
Hi,
I am trying to use jtwig as rendering engine for rendering the email body in my spring application.
And got this error:

```
java.lang.IncompatibleClassChangeError: class org.objectweb.asm.tree.ClassNode has interface org.objectweb.asm.ClassVisitor as super class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2491)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:836)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1278)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1143)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2491)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:836)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1278)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1143)
	at org.parboiled.transform.ParserTransformer.extendParserClass(ParserTransformer.java:43)
	at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:38)
	at org.parboiled.Parboiled.createParser(Parboiled.java:54)
	at org.jtwig.parser.parboiled.ParserContext.instance(ParserContext.java:31)
	at org.jtwig.parser.parboiled.ParboiledJtwigParser.parse(ParboiledJtwigParser.java:36)
	at org.jtwig.parser.cache.InMemoryConcurrentPersistentTemplateCache.get(InMemoryConcurrentPersistentTemplateCache.java:39)
	at org.jtwig.parser.CachedJtwigParser.parse(CachedJtwigParser.java:19)
	at org.jtwig.JtwigTemplate.render(JtwigTemplate.java:93)
	at org.jtwig.JtwigTemplate.render(JtwigTemplate.java:73)
```
 ```
public String test() {
        JtwigTemplate template = JtwigTemplate.classpathTemplate("templates/test.twig");

        String test = template.render(JtwigModel.newModel());;

        return test;
 }
```
Does anybody know the exact cause?

**Comment by lyncodev** [comment]
This is most likely two versions of the same ASM library in the classpath.

**Comment by redochka** [comment]
**jtwig-core** version **5.87.0.RELEASE** is pulling **parboiled-java** version **1.1.7** which is pulling **asm 5.0.3** which is causing this **IncompatibleClassChangeError**

I had to force **parboiled** version to **1.1.8** which depends on **asm 5.2**

```
<dependency>
    <groupId>org.jtwig</groupId>
    <artifactId>jtwig-core</artifactId>
    <version>5.87.0.RELEASE</version>
</dependency>
<dependency>
    <groupId>org.parboiled</groupId>
    <artifactId>parboiled-java</artifactId>
    <version>1.1.8</version>
</dependency>
<dependency>
    <groupId>org.jtwig</groupId>
    <artifactId>jtwig-core</artifactId>
    <version>5.87.0.RELEASE</version>
</dependency>
<dependency>
    <groupId>org.parboiled</groupId>
    <artifactId>parboiled-java</artifactId>
    <version>1.1.8</version>
</dependency>
```

**Comment by jantajov** [comment]
Issue seems not to be present anymore.
