### ISSUE TITLE
ParseException when using 'is null' with 'and'

### ISSUE THREAD

**Issue by bohnman** [jtwig/jtwig#357]
Version 5.86.RELEASE

Given the following template:

```
Hello {{name}}

{% if name is null and name %}
Done!
{% endif %}
```

Compiling this template will produce the following exception:

```
Exception in thread "main" org.jtwig.parser.ParseException: classpath:test.txt (Line: 3, Column: 20) -> If condition code island not closed
{% if name is null and name %}
                   ^
	at org.jtwig.parser.parboiled.ParboiledJtwigParser.parse(ParboiledJtwigParser.java:61)
	at org.jtwig.parser.cache.InMemoryConcurrentPersistentTemplateCache.get(InMemoryConcurrentPersistentTemplateCache.java:39)
	at org.jtwig.parser.CachedJtwigParser.parse(CachedJtwigParser.java:19)
	at org.jtwig.JtwigTemplate.render(JtwigTemplate.java:98)
	at org.jtwig.JtwigTemplate.render(JtwigTemplate.java:80)
	at test.Test.main(Test.java:11)
```

I have attached a sample project, [test.zip](https://github.com/jtwig/jtwig/files/1285719/test.zip), which you can run using your IDE or on the command line:

```
mvn exec:java
```

Thanks!

**Comment by bohnman** [comment]
Hi.  Just checking in to see if there is any feedback on this issue.  Thanks!

**Comment by TimYi** [comment]
I've got a similar error:
```
ERROR com.jiurong.configuration.servlet.ConfigurationListener - Error creating extended parser class: null
java.lang.RuntimeException: Error creating extended parser class: null
	at org.parboiled.Parboiled.createParser(Parboiled.java:58)
	at org.jtwig.parser.parboiled.ParserContext.instance(ParserContext.java:31)
	at org.jtwig.parser.parboiled.ParboiledJtwigParser.parse(ParboiledJtwigParser.java:37)
	at org.jtwig.parser.cache.InMemoryConcurrentPersistentTemplateCache.get(InMemoryConcurrentPersistentTemplateCache.java:39)
	at org.jtwig.parser.CachedJtwigParser.parse(CachedJtwigParser.java:19)
	at org.jtwig.JtwigTemplate.render(JtwigTemplate.java:98)
	at org.jtwig.JtwigTemplate.render(JtwigTemplate.java:74)
	at com.jiurong.configuration.Reporter.generateMarkdownReport(Reporter.java:15)
	at com.jiurong.configuration.servlet.ConfigurationListener.contextInitialized(ConfigurationListener.java:39)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4738)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5181)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.MethodVisitor.<init>(Unknown Source)
	at org.objectweb.asm.MethodVisitor.<init>(Unknown Source)
	at org.objectweb.asm.tree.MethodNode.<init>(Unknown Source)
	at org.objectweb.asm.tree.MethodNode.<init>(Unknown Source)
	at org.parboiled.transform.ClassNodeInitializer.visitMethod(ClassNodeInitializer.java:136)
	at org.objectweb.asm.ClassReader.b(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.parboiled.transform.ClassNodeInitializer.process(ClassNodeInitializer.java:63)
	at org.parboiled.transform.ParserTransformer.extendParserClass(ParserTransformer.java:44)
	at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:38)
	at org.parboiled.Parboiled.createParser(Parboiled.java:54)
	... 17 more
```
my template file is:
```
#显示指定值的配置内容：
{% for item in haveValueItems %}
{{item.name}}:
	描述：{{item.description}}
	是否必要：{{item.required}}
	默认值：{{item.defaultValue}}
	设置值：{{item.value}}
	取值域：{{item.domain}}
{% endfor %}

#有默认值但是没有显示指定值的配置内容：
{% for item in missedOptionalItems %}
{{item.name}}:
	描述：{{item.description}}
	是否必要：{{item.required}}
	默认值：{{item.defaultValue}}
	取值域：{{item.domain}}
{% endfor %}

#必选字段但是没有指定值的配置内容：
{% for item in missedRequiredItems %}
{{item.name}}:
	描述：{{item.description}}
	是否必要：{{item.required}}
	取值域：{{item.domain}}
{% endfor %}
```

**Comment by Ordiel** [comment]
Same here, sad to see there have been no updates :(

**Comment by luca-vercelli** [comment]
Similar problem here. The following gives an exception:

    X is not null ? X : Y

A workaround is to add parenthesis, however this is not really a solution

    (X is not null) ? X : Y

It seems there is a problem of precedence of operators here.
